### ISSUE TITLE
Can't Inject In Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by ernest290** [jeopardization/Zyklon#64]
When running the injector.jar I get prompted with this error. Any solutions?
![Screenshot from 2021-04-11 20-47-16](https://user-images.githubusercontent.com/28024059/114319108-f1e00980-9b07-11eb-8d3b-5c3822a39579.png)

**Comment by happyeggchen** [comment]
> When running the injector.jar I get prompted with this error. Any solutions?
> ![Screenshot from 2021-04-11 20-47-16](https://user-images.githubusercontent.com/28024059/114319108-f1e00980-9b07-11eb-8d3b-5c3822a39579.png)

how did u solve that
